absl-py alabaster argh asn1crypto astor astroid astropy atomicwrites attrs autopep8 Babel backcall backports.tempfile backports.weakref bcrypt beautifulsoup4 bitarray bkcharts bleach bokeh boto Bottleneck certifi cffi chardet Click cloudpickle colorama comtypes contextlib2 cryptography cycler Cython cytoolz dask decorator defusedxml diff-match-patch distributed docutils entrypoints fastcache filelock flake8 Flask fsspec future gevent glob2 greenlet grpcio h5py HeapDict html5lib hypothesis idna imageio imagesize importlib-metadata intervaltree ipykernel ipython ipywidgets isort itsdangerous jdcal jedi Jinja2 joblib json5 jsonschema jupyter jupyterlab keras keyring kiwisolver lazy-object-proxy llvmlite locket lxml Markdown MarkupSafe matplotlib mccabe mistune mock more-itertools mpmath multipledispatch nbconvert nbformat networkx nltk nose notebook numba numexpr numpy numpydoc olefile openpyxl packaging pandas pandocfilters paramiko parso partd path pathlib2 pathtools patsy pep8 pexpect pickleshare Pillow pkginfo pluggy ply prompt-toolkit protobuf psutil py pycodestyle pycosat pycparser pycrypto pydocstyle pyflakes Pygments pylint PyNaCl pyOpenSSL pyparsing pyreadline pyrsistent PySocks pytest pytest-arraydiff pytest-astropy pytest-astropy-header pytest-doctestplus pytest-openfiles pytest-remotedata python-dateutil python-jsonrpc-server python-language-server pytz PyWavelets pywinpty PyYAML pyzmq QDarkStyle QtAwesome qtconsole QtPy requests rope Rtree scikit-image scikit-learn scipy seaborn Send2Trash simplegeneric singledispatch six snowballstemmer sortedcollections sortedcontainers soupsieve Sphinx sphinxcontrib-applehelp sphinxcontrib-devhelp sphinxcontrib-htmlhelp sphinxcontrib-jsmath sphinxcontrib-qthelp sphinxcontrib-serializinghtml sphinxcontrib-websupport spyder spyder-kernels SQLAlchemy statsmodels sympy tblib tensorflow termcolor terminado testpath toolz tornado tqdm traitlets ujson unicodecsv urllib3 watchdog wcwidth webencodings Werkzeug widgetsnbextension wincertstore wrapt xlrd XlsxWriter xlwt xmltodict yapf zict zipp
 
 
  - backports.functools-lru-cache
  - backports.shutil-get-terminal-size
  - combo
  - et-xmlfile
  - msgpack
  - ipython-genutils
  - jupyter-client
  - jupyter-core
  - jupyter-console
  - jupyterlab-server
  - libarchive-c
  - prometheus-client
  - pyod
  - ruamel-yaml
  - suod
  - tables
  - win-inet-pton
  - win-unicode-console
  
 
  

atomicwrites beautifulsoup4 cryptography Cython html5lib keras matplotlib numpy pandas scikit-image scikit-learn scipy tensorflow 